### ISSUE TITLE
bffh.dhall Update per Import-Statement

### ISSUE THREAD

**Issue by vmario89** [elem74/fabaccess-config-generator#1]
Hi @elem74 - ich baue gerade für die JHV in Erlangen das Demo-Setup fertig und möchte den Config Generator dazu nutzen. Und da kam mir noch eine Idee für ein Feature bzw. Doku: und zwar kann man in Dhalls auch weitere Dhalls referenzieren (Importieren). Schau mal hier: https://docs.fab-access.org/books/fabaccess-konfiguration/page/hauptkonfiguration-bffhdhall#bkmrk-imports%2C-umgebungsva

vielleicht könnte man das gleich so angeben, dass sich die Nutzer ihre Haupt-Dhall konfigurieren und dann die ganzen Benutzer und Rollen und Co. in eine extern eingebettete File oder thematisch getrennte Files, die vom Config Generator gebaut werden. So wäre ggf. die Übersicht noch besser :-)

**Comment by elem74** [comment]
Ich wollte das eigentlich auch so einbauen, aber hatte Probleme mit der dhall-Syntax und hatte keine funktionierende Lösung gefunden.

Wenn du mir ein funktionierendes Beispiel mit mehreren dhall-Dateien liefern könntest, dann baue ich das gerne ein.

**Comment by elem74** [comment]
Im development-branch ist die Funktion eingebaut. Bitte teste mal mit deinem Demo-Setup, ob in der Praxis alles einwandfrei funktioniert. Dafür musst du folgende Konfiguration vornehmen:

## Einstellungen in der settings.ini
`fa_dhall_update` auf False
`fa_dhall_create` auf True
`fa_dhall_directory` zeigt auf den Ordner, der deine _bffh.dhall_ beinhaltet.

## Platzhalter in der bffh.dhall
```
roles = ./roles.dhall,
machines = ./machines.dhall,
actors = ./actors.dhall,
actor_connections = ./actorconnections.dhall,
```

**Comment by vmario89** [comment]
yeah das funktioniert wunderbar! <3 ich denke das kannst du in den master reinmergen =)

![grafik](https://github.com/user-attachments/assets/d2fda45e-747d-47d5-ae8b-ca874f00c387)

![grafik](https://github.com/user-attachments/assets/eb7caf18-6481-4b55-a239-de489ad54ccf)

bffh startet ohne Probleme, Client zeige alles wie gewohnt an
![grafik](https://github.com/user-attachments/assets/eb26bb48-3a12-40d4-beb6-fd9e1be50898)

**Comment by elem74** [comment]
Das Schalten der Steckdosen funktioniert auch problemlos? Ich habe hier keine Hardware zum Testen.

**Comment by vmario89** [comment]
ja das klappt super mit den Tasmota-Teilen!
