### ISSUE TITLE
Fehlende Dhall-Datei wird nicht angemeckert

### ISSUE THREAD

**Issue by vmario89** [elem74/fabaccess-config-generator#3]
Hey. Ich habe eine produktive bffh.dhall und würde die nicht durch den Generator überschreiben wollen. Stattdessen per Config eine neue schreiben lassen. Folgender Ordner existiert, aber beim Ausführen wird keine dhall dort geschrieben. Das Script warnt jedoch nicht, dass es keine dhall da hin schreiben konnte. Da ist noch ein kleiner Bug versteckt glaub ich.

`a_dhall_file = /opt/fabinfra/bffh-data/config/config-generator.dhall`

**Comment by vmario89** [comment]
ok sorry ich war kurz doof. hab Quatsch gemacht. Die CSV hatte immer noch ein Problem. Beim Generieren ist mir das nicht so richtig ins Auge gesprungen

**Comment by vmario89** [comment]
ok klappt trotzdem nicht. Es wird keine Datei geschrieben und es kommt auch kein Fehler. Egal, ob ich eine bestehende oder eine neue Datei angebe.

**Comment by elem74** [comment]
Ich schaue mir das die Tage mal an.

**Comment by elem74** [comment]
Also grundsätzlich kann das Skript keine neue dhall-Datei erzeugen, sondern immer nur eine bereits bestehende Datei aktualisieren. Wenn die in der settings.ini angegebene dhall-Datei nicht vorhanden ist, dann wird zwangsläufig ein Python-Fehler ausgeworfen und das Skript bricht ab.

Das Skript läuft bei mir unter Windows und Ubuntu fehlerfrei durch. Wenn die dhall-Datei nicht existiert, dann bricht es ab.

Hast du die Einstellung `fa_update_dhall` auch auf `True` gesetzt?

**Comment by vmario89** [comment]
danke! das hat geholfen! Ich hab nur aus Blindheit die Information mit dem ---||| GENERATOR START und ---||| GENERATOR END glorreich in der Doku überlesen und dann auch noch den Script-Output und dessen Warnung ignoriert. 2-in-1 Fehler meinerseits!
